### ISSUE TITLE
Need to document upcoming default naming scheme for constraints

### ISSUE THREAD

**Issue by thebiglabasky** [prisma/web#1842] opened 2021-06-07 09:57 UTC
As we are changing the constraint names (cf. https://github.com/prisma/prisma/issues/6680), we need to document the upgrade path for people to cope with the change.

1. Migrate your database so that the underlying constraints follow the new naming scheme
OR 
2. Introspect your database so that your Prisma schema reflects the database's underlying constraint names that are already there, thus preventing migrate to generate migrations for these in the future

**Comment by mhwelander** [comment] 2021-06-23 11:21
Duplicate of: #1869

**Closed as completed by mhwelander** 2021-06-23 11:21 UTC
Labels: type/docs
