### ISSUE TITLE
Docs crash and fail to load

### ISSUE THREAD

**Issue by raghavken** [prisma/web#810] opened 2020-09-01 20:36 UTC
When i try to access the prisma site and docs the content doesnt load, this is not due to my network as other websites load fine and fast but for some reason prisma site doesnt

**Comment by mhwelander** [comment] 2020-09-02 10:00
Related: #774

**Comment by nikolasburk** [comment] 2020-09-04 14:16
Closing this as a duplicate of: https://github.com/prisma/docs/issues/666

**Closed as completed by nikolasburk** 2020-09-04 14:16 UTC
Labels: web/bug, web/candidate
