### ISSUE TITLE
Delay when clicking right-hand TOC

### ISSUE THREAD

**Issue by mhwelander** [prisma/web#1006] opened 2020-11-10 13:14 UTC
Noticeable on longer pages: http://prisma.io/docs/reference/api-reference/prisma-schema-reference#boolean

**Comment by hrescak** [comment] 2020-12-08 13:50
I can't see any difference when clicking these - any chance you could attach a recording if this is still an issue?

**Comment by rahul3v** [comment] 2020-12-12 12:27
Try this steps at https://www.prisma.io/docs/concepts/components/prisma-client/crud

0. Test delay with some TOC to understand normal delay
1. Just search something on search bar, **lets say** `a`, 
2. Click on the outside of search box to exit, 
3. Now try to click on TOC,

**Result**: you will see a lot more delay then in normal case,

The **impact of delay** is **more if** the **search results are more**
also clicking on search bar again after all this steps, will cause a delay to popup search menu

problem Fixed in #1042

**Closed as completed** 2021-01-05 13:47 UTC
Labels: web/candidate

**Comment by rahul3v** [comment] 2021-01-06 06:25
@mhwelander, well the problem is still there !, as mentioned in earlier comment
