### ISSUE TITLE
Website bug report: Missing top padding on "Show CLI results"

### ISSUE THREAD

**Issue by nikolasburk** [prisma/web#1479] opened 2021-03-24 07:45 UTC
There seems to be missing top padding on the "Show CLI Results"-button on code blocks?

Example: https://www.prisma.io/docs/concepts/components/prisma-client/crud#create-a-single-record

![image](https://user-images.githubusercontent.com/4058327/112273057-34d35d80-8c7d-11eb-9e23-a73c2f1ac3ee.png)

**Comment by meletj** [comment] 2023-06-08 09:19
Duplicate of https://github.com/prisma/docs/issues/1467 - Already fixed


![Image](https://github.com/prisma/docs/assets/70962362/fea59031-a899-4940-98bf-f3e458c91ad7)

**Closed as completed by meletj** 2023-06-08 09:19 UTC
Labels: web/bug, website
