### ISSUE TITLE
Hide Netlify URLs from Google (SEO)

### ISSUE THREAD

**Issue by schickling** [prisma/web#265] opened 2020-04-27 09:55 UTC
We should make sure old docs Netlify URLs don't pop up on Google.

[Example: Search for "prisma relations"](https://www.google.com/search?q=prisma+relations&oq=prisma+relations&aqs=chrome..69i57j69i64j69i60l3.1652j0j1&sourceid=chrome&ie=UTF-8)

![image](https://user-images.githubusercontent.com/1567498/80359275-e2779a00-887d-11ea-94db-ef23d76e9c07.png)

![image](https://user-images.githubusercontent.com/1567498/80359322-f6230080-887d-11ea-9300-7dc8c485ff6f.png)

**Comment by nilubava** [comment] 2020-04-27 10:04
@janpio should this be moved to prisma1 docs?

**Comment by janpio** [comment] 2020-04-27 18:05
This applies to all our Netlify deployments:

Duplicate of https://github.com/prisma/prisma/issues/1949

**Closed as completed by janpio** 2020-04-27 18:05 UTC
