### ISSUE TITLE
https://www.prisma.io/docs/getting-started/setup-prisma/start-from-scratch-sql-typescript-mysql

### ISSUE THREAD

**Issue by TomasMoskala** [prisma/web#376] opened 2020-05-25 16:52 UTC
Before 
npx ts-node index.ts
I had to do 
npm config set cache <path>\npm-cache --global
because there is a space in the name of my Users folder
and also
npm install typescript
(would be nice to have it in instruction)

**Comment by ruheni** [comment] 2023-03-29 14:06
Hey Tomas 👋

Thanks for the suggestions. A few follow-up questions:
1. Could you share the error you encountered before setting the npm cache config?
2. Just curious: Do you have any particular reasons you prefer using `typescript` over the default, `ts-node` as a dependency?

I was unable to reproduce it on my end. I'll go ahead and close this issue for now. In case someone else runs into a similar issue, this issue should be of help to them. 🙂

**Closed as completed by ruheni** 2023-03-29 14:06 UTC
Labels: type/docs
