### ISSUE TITLE
Persist users db selection while going through the getting started guides

### ISSUE THREAD

**Issue by molebox** [prisma/web#2167] opened 2021-08-17 13:16 UTC
Currently when a user selects a database other than the default postgres database while going through the getting started guide, their selection will be reverted back to the default if they click on a left menu link then back to the guide. 

We can use React context to persist this selection instead, so that if the user selects msql then clicks away then back again, the guide will still have msql selected

**Comment by meletj** [comment] 2024-06-05 19:24
Closing as duplicate of #3392. Partially resolved as the 'next page' button will persist database selection. It still needs to be fixed on the left-hand menu.

**Closed as completed by meletj** 2024-06-05 19:24 UTC
Labels: website
